/**
 * Moedas ISO 4217 (lista ampla para select “global”).
 * Nomes em português onde comuns; restante pelo código.
 */
export type GlobalCurrencyOption = { code: string; label: string }

const PAIRS: [string, string][] = [
  ['AED', 'Dirham dos EAU'],
  ['AFN', 'Afegani'],
  ['ALL', 'Lek albanês'],
  ['AMD', 'Dram arménio'],
  ['ANG', 'Florim das Antilhas'],
  ['AOA', 'Kwanza'],
  ['ARS', 'Peso argentino'],
  ['AUD', 'Dólar australiano'],
  ['AWG', 'Florim arubano'],
  ['AZN', 'Manat azeri'],
  ['BAM', 'Marco conversível'],
  ['BBD', 'Dólar barbadense'],
  ['BDT', 'Taka'],
  ['BGN', 'Lev búlgaro'],
  ['BHD', 'Dinar bareinita'],
  ['BIF', 'Franco burundiano'],
  ['BMD', 'Dólar bermudense'],
  ['BND', 'Dólar bruneano'],
  ['BOB', 'Boliviano'],
  ['BRL', 'Real brasileiro'],
  ['BSD', 'Dólar bahamense'],
  ['BTN', 'Ngultrum'],
  ['BWP', 'Pula'],
  ['BYN', 'Rublo bielorrusso'],
  ['BZD', 'Dólar belizenho'],
  ['CAD', 'Dólar canadense'],
  ['CDF', 'Franco congolês'],
  ['CHF', 'Franco suíço'],
  ['CLP', 'Peso chileno'],
  ['CNY', 'Yuan renminbi'],
  ['COP', 'Peso colombiano'],
  ['CRC', 'Colón costa-riquenho'],
  ['CUP', 'Peso cubano'],
  ['CVE', 'Escudo cabo-verdiano'],
  ['CZK', 'Coroa checa'],
  ['DJF', 'Franco jibutiano'],
  ['DKK', 'Coroa dinamarquesa'],
  ['DOP', 'Peso dominicano'],
  ['DZD', 'Dinar argelino'],
  ['EGP', 'Libra egípcia'],
  ['ERN', 'Nakfa'],
  ['ETB', 'Birr etíope'],
  ['EUR', 'Euro'],
  ['FJD', 'Dólar fijiano'],
  ['FKP', 'Libra das Ilhas Malvinas'],
  ['GBP', 'Libra esterlina'],
  ['GEL', 'Lari georgiano'],
  ['GHS', 'Cedi'],
  ['GIP', 'Libra de Gibraltar'],
  ['GMD', 'Dalasi'],
  ['GNF', 'Franco guineense'],
  ['GTQ', 'Quetzal'],
  ['GYD', 'Dólar guianense'],
  ['HKD', 'Dólar de Hong Kong'],
  ['HNL', 'Lempira'],
  ['HTG', 'Gourde'],
  ['HUF', 'Forint'],
  ['IDR', 'Rupia indonésia'],
  ['ILS', 'Novo shekel israelita'],
  ['INR', 'Rupia indiana'],
  ['IQD', 'Dinar iraquiano'],
  ['IRR', 'Rial iraniano'],
  ['ISK', 'Coroa islandesa'],
  ['JMD', 'Dólar jamaicano'],
  ['JOD', 'Dinar jordaniano'],
  ['JPY', 'Iene'],
  ['KES', 'Xelim queniano'],
  ['KGS', 'Som'],
  ['KHR', 'Riel'],
  ['KMF', 'Franco comoriano'],
  ['KRW', 'Won sul-coreano'],
  ['KWD', 'Dinar kuwaitiano'],
  ['KYD', 'Dólar das Ilhas Caimão'],
  ['KZT', 'Tenge'],
  ['LAK', 'Kip'],
  ['LBP', 'Libra libanesa'],
  ['LKR', 'Rupia do Sri Lanka'],
  ['LRD', 'Dólar liberiano'],
  ['LSL', 'Loti'],
  ['LYD', 'Dinar líbio'],
  ['MAD', 'Dirham marroquino'],
  ['MDL', 'Leu moldavo'],
  ['MGA', 'Ariary'],
  ['MKD', 'Denar'],
  ['MMK', 'Kyat'],
  ['MNT', 'Tugrik'],
  ['MOP', 'Pataca'],
  ['MRU', 'Ouguiya'],
  ['MUR', 'Rupia mauriciana'],
  ['MVR', 'Rufiyaa'],
  ['MWK', 'Kwacha malauiano'],
  ['MXN', 'Peso mexicano'],
  ['MYR', 'Ringgit'],
  ['MZN', 'Metical'],
  ['NAD', 'Dólar namibiano'],
  ['NGN', 'Naira'],
  ['NIO', 'Córdoba nicaraguense'],
  ['NOK', 'Coroa norueguesa'],
  ['NPR', 'Rupia nepalesa'],
  ['NZD', 'Dólar neozelandês'],
  ['OMR', 'Rial omanense'],
  ['PAB', 'Balboa'],
  ['PEN', 'Sol peruano'],
  ['PGK', 'Kina'],
  ['PHP', 'Peso filipino'],
  ['PKR', 'Rupia paquistanesa'],
  ['PLN', 'Zloty'],
  ['PYG', 'Guarani'],
  ['QAR', 'Rial catarense'],
  ['RON', 'Leu romeno'],
  ['RSD', 'Dinar sérvio'],
  ['RUB', 'Rublo russo'],
  ['RWF', 'Franco ruandês'],
  ['SAR', 'Rial saudita'],
  ['SBD', 'Dólar das Ilhas Salomão'],
  ['SCR', 'Rupia seichelense'],
  ['SDG', 'Libra sudanesa'],
  ['SEK', 'Coroa sueca'],
  ['SGD', 'Dólar singapuriano'],
  ['SHP', 'Libra de Santa Helena'],
  ['SLE', 'Leone'],
  ['SOS', 'Xelim somali'],
  ['SRD', 'Dólar surinamês'],
  ['SSP', 'Libra sul-sudanesa'],
  ['STN', 'Dobra'],
  ['SVC', 'Colón salvadorenho'],
  ['SYP', 'Libra síria'],
  ['SZL', 'Lilangeni'],
  ['THB', 'Baht'],
  ['TJS', 'Somoni'],
  ['TMT', 'Manat turcomeno'],
  ['TND', 'Dinar tunisiano'],
  ['TOP', "Pa'anga"],
  ['TRY', 'Lira turca'],
  ['TTD', 'Dólar de Trindade e Tobago'],
  ['TWD', 'Dólar taiwanês'],
  ['TZS', 'Xelim tanzaniano'],
  ['UAH', 'Hryvnia'],
  ['UGX', 'Xelim ugandense'],
  ['USD', 'Dólar dos EUA'],
  ['UYU', 'Peso uruguaio'],
  ['UZS', 'Som uzbeque'],
  ['VES', 'Bolívar venezuelano'],
  ['VND', 'Dong'],
  ['VUV', 'Vatu'],
  ['WST', 'Tala'],
  ['XAF', 'Franco CFA (BEAC)'],
  ['XCD', 'Dólar do Caribe Oriental'],
  ['XOF', 'Franco CFA (BCEAO)'],
  ['XPF', 'Franco CFP'],
  ['YER', 'Rial iemenita'],
  ['ZAR', 'Rand'],
  ['ZMW', 'Kwacha zambiano'],
]

export const GLOBAL_CURRENCY_OPTIONS: GlobalCurrencyOption[] = PAIRS.map(([code, name]) => ({
  code,
  label: `${code} — ${name}`,
})).sort((a, b) => a.code.localeCompare(b.code))
