'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  Target, Zap, TrendingUp, Users, Cpu, AlertTriangle, CheckCircle2,
  Circle, Loader2, Plus, X, Pencil, ChevronDown, ChevronUp,
  Flame, Star, RefreshCw, Eye, EyeOff, Trophy, ArrowUp, ArrowDown,
} from 'lucide-react'

// ─────────────────────────────────────────────────────────────────────────────
// Tipos
// ─────────────────────────────────────────────────────────────────────────────

type Task = {
  id: string; title: string; description: string | null
  category: 'ESCALA' | 'EFICIENCIA' | 'INFRA' | 'GESTAO'
  impact: number; urgency: number; priorityScore: number
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW'
  status: 'TODO' | 'DOING' | 'DONE' | 'ARCHIVED'
  revenueImpact: number | null; dueDate: string | null
  completedAt: string | null; autoGenerated: boolean
  createdAt: string
}

type Stats = { byStatus: Record<string,number>; byCategory: Record<string,number>; escalaCompletedPct: number; escalaAlert: boolean }

type Insights = {
  period: { year: number; month: number; daysLeft: number; dailyNeed: number }
  revenue: { realized: number; goal: number; pct: number; grossMargin: number; marginPct: number; salesCount: number; onTrack: boolean }
  burnRate: { spent: number; limit: number; pct: number; alert: boolean; remaining: number }
  cac: { value: number; alert: boolean; status: string; limit: number }
  monthlyRevenue: { month: string; revenue: number; margin: number }[]
  taskStats: Record<string, number>
  alerts: { messages: string[] }
}

// ─────────────────────────────────────────────────────────────────────────────
// Constantes de UI
// ─────────────────────────────────────────────────────────────────────────────

const CATEGORY_CONFIG = {
  ESCALA:     { label: 'Escala',     icon: TrendingUp, color: 'text-blue-600',   bg: 'bg-blue-50 dark:bg-blue-950/20',   border: 'border-blue-200', badge: 'bg-blue-100 text-blue-700' },
  EFICIENCIA: { label: 'Eficiência', icon: Target,     color: 'text-violet-600', bg: 'bg-violet-50 dark:bg-violet-950/20', border: 'border-violet-200', badge: 'bg-violet-100 text-violet-700' },
  INFRA:      { label: 'Infra',      icon: Cpu,        color: 'text-teal-600',   bg: 'bg-teal-50 dark:bg-teal-950/20',   border: 'border-teal-200', badge: 'bg-teal-100 text-teal-700' },
  GESTAO:     { label: 'Gestão',     icon: Users,      color: 'text-amber-600',  bg: 'bg-amber-50 dark:bg-amber-950/20', border: 'border-amber-200', badge: 'bg-amber-100 text-amber-700' },
}

const PRIORITY_CONFIG = {
  CRITICAL: { label: 'Crítica',   color: 'text-red-600',    dot: 'bg-red-500',    badge: 'bg-red-100 text-red-700' },
  HIGH:     { label: 'Alta',      color: 'text-orange-600', dot: 'bg-orange-500', badge: 'bg-orange-100 text-orange-700' },
  MEDIUM:   { label: 'Média',     color: 'text-amber-600',  dot: 'bg-amber-500',  badge: 'bg-amber-100 text-amber-700' },
  LOW:      { label: 'Baixa',     color: 'text-zinc-500',   dot: 'bg-zinc-400',   badge: 'bg-zinc-100 text-zinc-600' },
}

const STATUS_LABELS = { TODO: 'A Fazer', DOING: 'Em Andamento', DONE: 'Concluído' }

const brl = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 })
const brlFull = (v: number) => v.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

// ─────────────────────────────────────────────────────────────────────────────
// Barra de progresso
// ─────────────────────────────────────────────────────────────────────────────

function ProgressBar({ pct, color = 'bg-primary-600', height = 'h-3' }: { pct: number; color?: string; height?: string }) {
  return (
    <div className={`w-full ${height} rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden`}>
      <div className={`${height} rounded-full transition-all duration-700 ${color}`} style={{ width: `${Math.min(100, pct)}%` }} />
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Card de KPI
// ─────────────────────────────────────────────────────────────────────────────

function KpiCard({ label, value, sub, pct, pctColor, alert }: {
  label: string; value: string; sub?: string; pct?: number; pctColor?: string; alert?: boolean
}) {
  return (
    <div className={`rounded-2xl border p-4 ${alert ? 'border-red-300 bg-red-50 dark:bg-red-950/10' : 'border-zinc-200 dark:border-zinc-700 bg-white dark:bg-ads-dark-card'}`}>
      <p className="text-xs font-semibold text-zinc-500 uppercase mb-1">{label}</p>
      <p className={`text-2xl font-bold ${alert ? 'text-red-600' : 'text-zinc-900 dark:text-white'}`}>{value}</p>
      {sub && <p className={`text-xs mt-0.5 ${alert ? 'text-red-500' : 'text-zinc-400'}`}>{sub}</p>}
      {pct !== undefined && <div className="mt-2"><ProgressBar pct={pct} color={pctColor} /></div>}
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Card de Tarefa
// ─────────────────────────────────────────────────────────────────────────────

function TaskCard({ task, onStatusChange, onEdit, compact = false }: {
  task: Task; onStatusChange: (id: string, status: string) => void
  onEdit?: (t: Task) => void; compact?: boolean
}) {
  const cat  = CATEGORY_CONFIG[task.category]
  const pri  = PRIORITY_CONFIG[task.priority]
  const CatIcon = cat.icon
  const [open, setOpen] = useState(false)

  const nextStatus: Record<string, string | null> = { TODO: 'DOING', DOING: 'DONE', DONE: null }
  const prevStatus: Record<string, string | null> = { DOING: 'TODO', DONE: 'DOING', TODO: null }

  return (
    <div className={`rounded-xl border ${task.status === 'DONE' ? 'border-zinc-100 dark:border-zinc-800 opacity-60' : cat.border} bg-white dark:bg-ads-dark-card p-3.5 transition-all hover:shadow-sm`}>
      <div className="flex items-start gap-2.5">
        {/* Score Badge */}
        <div className={`shrink-0 w-10 h-10 rounded-lg flex flex-col items-center justify-center text-center ${task.priority === 'CRITICAL' ? 'bg-red-100 dark:bg-red-950/30' : task.priority === 'HIGH' ? 'bg-orange-100' : 'bg-zinc-50 dark:bg-zinc-800'}`}>
          <span className={`text-base font-black leading-none ${pri.color}`}>{task.priorityScore}</span>
          <span className="text-[8px] text-zinc-400 uppercase">score</span>
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-1.5 flex-wrap mb-0.5">
            <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold ${cat.badge} flex items-center gap-0.5`}>
              <CatIcon className="w-2.5 h-2.5" />{cat.label}
            </span>
            <span className={`px-1.5 py-0.5 rounded text-[10px] font-bold ${pri.badge}`}>{pri.label}</span>
            {task.autoGenerated && <span className="px-1.5 py-0.5 rounded text-[10px] bg-zinc-100 text-zinc-500">⚡ Auto</span>}
          </div>
          <p className={`text-sm font-semibold leading-snug ${task.status === 'DONE' ? 'line-through text-zinc-400' : ''}`}>{task.title}</p>
          {!compact && task.description && (
            <button onClick={() => setOpen((v) => !v)} className="text-[11px] text-zinc-400 hover:text-zinc-600 flex items-center gap-0.5 mt-0.5">
              {open ? <><ChevronUp className="w-3 h-3" />Ocultar</> : <><ChevronDown className="w-3 h-3" />Ver mais</>}
            </button>
          )}
          {open && <p className="text-xs text-zinc-500 mt-1 leading-relaxed">{task.description}</p>}
          {task.revenueImpact && (
            <p className="text-[11px] text-green-600 font-semibold mt-1">💰 Impacto estimado: {brlFull(task.revenueImpact)}</p>
          )}
        </div>

        {/* Controles */}
        <div className="flex flex-col gap-1 shrink-0">
          {prevStatus[task.status] && (
            <button onClick={() => onStatusChange(task.id, prevStatus[task.status]!)}
              className="p-1 rounded hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors" title="Voltar">
              <ArrowUp className="w-3.5 h-3.5 text-zinc-400" />
            </button>
          )}
          {nextStatus[task.status] && (
            <button onClick={() => onStatusChange(task.id, nextStatus[task.status]!)}
              className="p-1 rounded hover:bg-green-50 dark:hover:bg-green-950/20 transition-colors" title="Avançar">
              <ArrowDown className="w-3.5 h-3.5 text-green-500" />
            </button>
          )}
          {onEdit && task.status !== 'DONE' && (
            <button onClick={() => onEdit(task)} className="p-1 rounded hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors">
              <Pencil className="w-3.5 h-3.5 text-zinc-400" />
            </button>
          )}
        </div>
      </div>
    </div>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Formulário de Tarefa
// ─────────────────────────────────────────────────────────────────────────────

function TaskForm({ onSave, onCancel, initial }: {
  onSave: (d: Partial<Task>) => Promise<void>
  onCancel: () => void
  initial?: Partial<Task>
}) {
  const [title, setTitle]           = useState(initial?.title ?? '')
  const [description, setDesc]      = useState(initial?.description ?? '')
  const [category, setCategory]     = useState(initial?.category ?? 'ESCALA')
  const [impact, setImpact]         = useState(initial?.impact ?? 5)
  const [urgency, setUrgency]       = useState(initial?.urgency ?? 5)
  const [revenueImpact, setRevImp]  = useState(initial?.revenueImpact ? String(initial.revenueImpact) : '')
  const [saving, setSaving]         = useState(false)
  const score = impact * 2 + urgency

  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true)
    await onSave({ title, description: description || undefined, category, impact, urgency, revenueImpact: revenueImpact ? parseFloat(revenueImpact) : undefined })
    setSaving(false)
  }

  return (
    <form onSubmit={submit} className="rounded-2xl border border-primary-200 bg-primary-50 dark:bg-primary-950/10 p-4 space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="font-bold text-sm">{initial ? 'Editar Tarefa' : '+ Nova Tarefa'}</h3>
        <button type="button" onClick={onCancel}><X className="w-4 h-4 text-zinc-400" /></button>
      </div>

      <input required value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Título da tarefa..." className="input-field" />
      <textarea rows={2} value={description} onChange={(e) => setDesc(e.target.value)} placeholder="Contexto e próximos passos..." className="input-field resize-none" />

      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="block text-xs font-semibold mb-1">Categoria</label>
          <select value={category} onChange={(e) => setCategory(e.target.value as typeof category)} className="input-field">
            {Object.entries(CATEGORY_CONFIG).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-xs font-semibold mb-1">Impacto Financeiro Estimado</label>
          <input type="number" value={revenueImpact} onChange={(e) => setRevImp(e.target.value)} className="input-field" placeholder="Ex: 50000" />
        </div>
      </div>

      {/* Sliders de Impacto × Urgência */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <label className="block text-xs font-semibold mb-1">Impacto no Faturamento: <span className="text-primary-600 font-black">{impact}</span>/10</label>
          <input type="range" min={1} max={10} value={impact} onChange={(e) => setImpact(parseInt(e.target.value))}
            className="w-full accent-primary-600" />
        </div>
        <div>
          <label className="block text-xs font-semibold mb-1">Urgência: <span className="text-primary-600 font-black">{urgency}</span>/10</label>
          <input type="range" min={1} max={10} value={urgency} onChange={(e) => setUrgency(parseInt(e.target.value))}
            className="w-full accent-primary-600" />
        </div>
      </div>

      <div className="flex items-center justify-between">
        <div className={`px-3 py-1.5 rounded-lg text-sm font-bold ${score >= 25 ? 'bg-red-100 text-red-700' : score >= 18 ? 'bg-orange-100 text-orange-700' : 'bg-zinc-100 text-zinc-600'}`}>
          Score: {score} — {score >= 25 ? 'CRÍTICA 🚨' : score >= 18 ? 'ALTA 🔥' : score >= 12 ? 'MÉDIA' : 'BAIXA'}
        </div>
        <div className="flex gap-2">
          <button type="button" onClick={onCancel} className="btn-secondary text-sm">Cancelar</button>
          <button type="submit" disabled={saving || !title.trim()} className="btn-primary text-sm flex items-center gap-1.5">
            {saving ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <CheckCircle2 className="w-3.5 h-3.5" />}
            Salvar
          </button>
        </div>
      </div>
    </form>
  )
}

// ─────────────────────────────────────────────────────────────────────────────
// Component Principal
// ─────────────────────────────────────────────────────────────────────────────

export function CeoCommandCenter() {
  const [tasks, setTasks]       = useState<Task[]>([])
  const [stats, setStats]       = useState<Stats | null>(null)
  const [insights, setInsights] = useState<Insights | null>(null)
  const [loading, setLoading]   = useState(true)
  const [focusMode, setFocusMode] = useState(false)
  const [showForm, setShowForm] = useState(false)
  const [editTask, setEditTask] = useState<Task | null>(null)
  const [filterCat, setFilterCat] = useState<string>('')
  const [filterStatus, setFilterStatus] = useState<string>('TODO,DOING')
  const quickRef = useRef<HTMLInputElement>(null)
  const [quickTitle, setQuickTitle] = useState('')

  const loadTasks = useCallback(async () => {
    const p = new URLSearchParams()
    if (filterCat) p.set('category', filterCat)
    const r = await fetch(`/api/admin/ceo-tasks?${p}`)
    if (r.ok) {
      const j = await r.json()
      setTasks(j.tasks ?? []); setStats(j.stats ?? null)
    }
  }, [filterCat])

  const loadInsights = useCallback(async () => {
    const r = await fetch('/api/admin/ceo-tasks/insights')
    if (r.ok) setInsights(await r.json())
  }, [])

  const load = useCallback(async () => {
    setLoading(true)
    await Promise.all([loadTasks(), loadInsights()])
    setLoading(false)
  }, [loadTasks, loadInsights])

  useEffect(() => { load() }, [load])

  const statusChange = async (id: string, status: string) => {
    await fetch(`/api/admin/ceo-tasks/${id}`, {
      method: 'PATCH', headers: { 'Content-Type': 'application/json' },
      body:   JSON.stringify({ status }),
    })
    loadTasks()
  }

  const saveTask = async (data: Partial<Task>) => {
    if (editTask) {
      await fetch(`/api/admin/ceo-tasks/${editTask.id}`, {
        method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data),
      })
      setEditTask(null)
    } else {
      await fetch('/api/admin/ceo-tasks', {
        method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data),
      })
      setShowForm(false)
    }
    loadTasks()
  }

  const quickAdd = async (e: React.FormEvent) => {
    e.preventDefault(); if (!quickTitle.trim()) return
    await fetch('/api/admin/ceo-tasks', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ title: quickTitle, category: 'ESCALA', impact: 5, urgency: 5 }),
    })
    setQuickTitle(''); loadTasks()
  }

  const filtered = tasks.filter((t) => {
    const statuses = filterStatus.split(',')
    return statuses.includes(t.status)
  })

  const topTasks     = [...tasks].filter((t) => t.status !== 'DONE').slice(0, 3)
  const kanbanGroups: Record<string, Task[]> = { TODO: [], DOING: [], DONE: [] }
  for (const t of tasks) { if (t.status !== 'ARCHIVED') (kanbanGroups[t.status] ?? []).push(t) }

  // ─── Render ───────────────────────────────────────────────────────────────
  return (
    <div className="space-y-6 max-w-7xl">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-black tracking-tight flex items-center gap-2">
            <Trophy className="w-6 h-6 text-amber-500" />
            CEO Command Center
          </h1>
          <p className="text-sm text-zinc-500 mt-0.5">Road to <strong className="text-primary-600">R$ 1.000.000/mês</strong> — OKR + Matriz de Impacto</p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button onClick={() => setFocusMode((v) => !v)}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-bold border transition-colors ${focusMode ? 'bg-primary-600 text-white border-primary-600' : 'border-zinc-200 dark:border-zinc-700 text-zinc-600 hover:bg-zinc-50'}`}>
            {focusMode ? <Eye className="w-4 h-4" /> : <EyeOff className="w-4 h-4" />}
            {focusMode ? 'Modo Foco ATIVO' : 'Modo Foco'}
          </button>
          <button onClick={load} className="p-2 rounded-xl border border-zinc-200 dark:border-zinc-700 hover:bg-zinc-50 transition-colors">
            <RefreshCw className="w-4 h-4 text-zinc-400" />
          </button>
        </div>
      </div>

      {/* ── Alertas automáticos ─────────────────────────────────────────────── */}
      {insights?.alerts?.messages && insights.alerts.messages.length > 0 && (
        <div className="space-y-2">
          {insights.alerts.messages.map((msg, i) => (
            <div key={i} className="rounded-xl border border-red-300 bg-red-50 dark:bg-red-950/10 px-4 py-2.5 text-sm text-red-700 flex items-center gap-2 font-semibold">
              <AlertTriangle className="w-4 h-4 shrink-0" />{msg}
            </div>
          ))}
        </div>
      )}

      {/* ── Alerta de Escala ─────────────────────────────────────────────── */}
      {stats?.escalaAlert && (
        <div className="rounded-xl border border-amber-300 bg-amber-50 dark:bg-amber-950/10 px-4 py-3 text-sm text-amber-800 flex items-start gap-2">
          <Flame className="w-4 h-4 shrink-0 mt-0.5 text-amber-600" />
          <span>
            <strong>CEO, você está focado demais no operacional!</strong>{' '}
            Apenas {stats.escalaCompletedPct}% das tarefas concluídas nos últimos 7 dias foram de <strong>Escala</strong>.
            A meta é ≥ 50%.
          </span>
        </div>
      )}

      {/* ── KPI Dashboard ───────────────────────────────────────────────────── */}
      {loading ? (
        <div className="flex justify-center py-8"><Loader2 className="w-6 h-6 animate-spin text-zinc-400" /></div>
      ) : insights && (
        <>
          {/* Progress de Faturamento */}
          <div className="rounded-2xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-ads-dark-card p-5 space-y-3">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div>
                <p className="text-xs font-semibold text-zinc-500 uppercase">Faturamento — {new Date().toLocaleString('pt-BR', { month: 'long', year: 'numeric' })}</p>
                <div className="flex items-baseline gap-2 mt-0.5">
                  <span className="text-3xl font-black text-primary-600">{brl(insights.revenue.realized)}</span>
                  <span className="text-zinc-400 text-sm">/ {brl(insights.revenue.goal)}</span>
                  <span className={`text-sm font-bold px-2 py-0.5 rounded-full ${insights.revenue.onTrack ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
                    {insights.revenue.pct}% {insights.revenue.onTrack ? '✅ No ritmo' : '⚠️ Atrás'}
                  </span>
                </div>
              </div>
              <div className="text-right text-xs space-y-0.5">
                <p className="text-zinc-500">{insights.period.daysLeft} dias restantes</p>
                <p className="font-bold text-primary-600">Precisa: {brl(insights.period.dailyNeed)}/dia</p>
              </div>
            </div>
            <ProgressBar pct={insights.revenue.pct} color={insights.revenue.pct >= 70 ? 'bg-green-500' : insights.revenue.pct >= 40 ? 'bg-amber-500' : 'bg-primary-600'} height="h-4" />
            <div className="grid grid-cols-3 gap-3 text-center text-xs">
              <div><p className="text-zinc-400">Margem Bruta</p><p className="font-bold text-green-600">{brl(insights.revenue.grossMargin)} ({insights.revenue.marginPct}%)</p></div>
              <div><p className="text-zinc-400">Vendas Entregues</p><p className="font-bold">{insights.revenue.salesCount}</p></div>
              <div><p className="text-zinc-400">Ticket Médio</p><p className="font-bold">{insights.revenue.salesCount > 0 ? brl(insights.revenue.realized / insights.revenue.salesCount) : '—'}</p></div>
            </div>
          </div>

          {/* KPIs secundários */}
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <KpiCard
              label="Burn Rate (Compras)"
              value={brl(insights.burnRate.spent)}
              sub={`${insights.burnRate.pct}% do teto de ${brl(insights.burnRate.limit)} · Sobra: ${brl(insights.burnRate.remaining)}`}
              pct={insights.burnRate.pct}
              pctColor={insights.burnRate.pct >= 80 ? 'bg-red-500' : insights.burnRate.pct >= 60 ? 'bg-amber-500' : 'bg-teal-500'}
              alert={insights.burnRate.alert}
            />
            <KpiCard
              label="CAC — Custo por Cliente"
              value={insights.cac.value > 0 ? brl(insights.cac.value) : 'Sem dados'}
              sub={`Limite: ${brl(insights.cac.limit)}`}
              alert={insights.cac.alert}
            />
            <div className="rounded-2xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-ads-dark-card p-4">
              <p className="text-xs font-semibold text-zinc-500 uppercase mb-2">Distribuição de Tarefas</p>
              {stats && Object.entries(CATEGORY_CONFIG).map(([cat, cfg]) => {
                const count = stats.byCategory[cat] ?? 0
                const total = Object.values(stats.byCategory).reduce((a, b) => a + b, 0)
                const pct = total > 0 ? Math.round(count / total * 100) : 0
                const CatIcon = cfg.icon
                return (
                  <div key={cat} className="flex items-center gap-2 mb-1.5">
                    <CatIcon className={`w-3 h-3 ${cfg.color} shrink-0`} />
                    <span className="text-xs text-zinc-600 flex-1">{cfg.label}</span>
                    <div className="w-24 h-1.5 rounded-full bg-zinc-100 dark:bg-zinc-800 overflow-hidden">
                      <div className={`h-full rounded-full ${cat === 'ESCALA' ? 'bg-blue-500' : cat === 'EFICIENCIA' ? 'bg-violet-500' : cat === 'INFRA' ? 'bg-teal-500' : 'bg-amber-500'}`} style={{ width: `${pct}%` }} />
                    </div>
                    <span className="text-xs font-bold w-8 text-right">{count}</span>
                  </div>
                )
              })}
            </div>
          </div>

          {/* Sparkline mensal */}
          <div className="rounded-2xl border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-ads-dark-card p-4">
            <p className="text-xs font-semibold text-zinc-500 uppercase mb-3">Histórico de Faturamento (6 meses)</p>
            <div className="flex items-end gap-1 h-16">
              {insights.monthlyRevenue.map((m) => {
                const max = Math.max(...insights.monthlyRevenue.map((x) => x.revenue), 1)
                const h   = Math.max(4, Math.round((m.revenue / max) * 64))
                return (
                  <div key={m.month} className="flex-1 flex flex-col items-center gap-1">
                    <div className="w-full bg-primary-500 dark:bg-primary-600 rounded-t-sm transition-all" style={{ height: `${h}px` }} title={brl(m.revenue)} />
                    <span className="text-[9px] text-zinc-400">{m.month}</span>
                  </div>
                )
              })}
            </div>
          </div>
        </>
      )}

      {/* ── Modo Foco — Top 3 Tarefas ───────────────────────────────────────── */}
      {focusMode && (
        <div className="rounded-2xl border-2 border-primary-400 bg-primary-50 dark:bg-primary-950/10 p-5 space-y-3">
          <div className="flex items-center gap-2">
            <Star className="w-5 h-5 text-primary-600 fill-primary-600" />
            <h2 className="font-black text-lg">Modo Foco — Suas 3 Prioridades Agora</h2>
          </div>
          <p className="text-xs text-zinc-500">Esqueça o resto. Resolva isso primeiro.</p>
          <div className="space-y-2">
            {topTasks.length === 0
              ? <p className="text-zinc-400 text-sm text-center py-4">Nenhuma tarefa ativa — adicione suas próximas ações.</p>
              : topTasks.map((t, i) => (
                <div key={t.id} className="flex gap-3 items-start">
                  <div className="w-8 h-8 rounded-full bg-primary-600 text-white flex items-center justify-center font-black text-sm shrink-0">{i + 1}</div>
                  <TaskCard task={t} onStatusChange={statusChange} compact />
                </div>
              ))
            }
          </div>
        </div>
      )}

      {/* ── Quick Task ──────────────────────────────────────────────────────── */}
      <form onSubmit={quickAdd} className="flex gap-2">
        <div className="relative flex-1">
          <Zap className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-400" />
          <input ref={quickRef} value={quickTitle} onChange={(e) => setQuickTitle(e.target.value)}
            placeholder="⚡ Quick Task — capture sua ideia agora (Enter para salvar)..."
            className="input-field pl-9 py-3 text-sm" />
        </div>
        <button type="submit" disabled={!quickTitle.trim()} className="btn-primary px-5 text-sm flex items-center gap-1.5">
          <Plus className="w-4 h-4" />Salvar
        </button>
      </form>

      {/* ── Kanban ──────────────────────────────────────────────────────────── */}
      {!focusMode && (
        <div className="space-y-4">
          {/* Filtros */}
          <div className="flex flex-wrap gap-2 items-center justify-between">
            <div className="flex gap-1.5 flex-wrap">
              <button onClick={() => setFilterStatus('TODO,DOING')} className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-colors ${filterStatus === 'TODO,DOING' ? 'bg-primary-600 text-white border-primary-600' : 'border-zinc-200 dark:border-zinc-700'}`}>
                Ativas
              </button>
              <button onClick={() => setFilterStatus('DONE')} className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-colors ${filterStatus === 'DONE' ? 'bg-primary-600 text-white border-primary-600' : 'border-zinc-200 dark:border-zinc-700'}`}>
                Concluídas
              </button>
              {Object.entries(CATEGORY_CONFIG).map(([k, v]) => (
                <button key={k} onClick={() => setFilterCat(filterCat === k ? '' : k)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold border transition-colors ${filterCat === k ? v.badge + ' border-transparent' : 'border-zinc-200 dark:border-zinc-700 text-zinc-600'}`}>
                  {v.label}
                </button>
              ))}
            </div>
            <button onClick={() => setShowForm(true)} className="btn-primary text-sm flex items-center gap-1.5 px-4 py-2">
              <Plus className="w-4 h-4" />Nova Tarefa
            </button>
          </div>

          {/* Formulário */}
          {showForm && !editTask && (
            <TaskForm onSave={saveTask} onCancel={() => setShowForm(false)} />
          )}
          {editTask && (
            <TaskForm onSave={saveTask} onCancel={() => setEditTask(null)} initial={editTask} />
          )}

          {/* Kanban Grid */}
          <div className="grid md:grid-cols-3 gap-4">
            {(Object.entries(kanbanGroups) as [string, Task[]][]).map(([status, items]) => {
              const statusItems = filterStatus.includes(status) ? filtered.filter((t) => t.status === status) : []
              if (!filterStatus.includes(status)) return null
              return (
                <div key={status} className="space-y-2">
                  <div className="flex items-center gap-2 px-1">
                    {status === 'TODO'  && <Circle className="w-3.5 h-3.5 text-zinc-400" />}
                    {status === 'DOING' && <Loader2 className="w-3.5 h-3.5 text-blue-500 animate-spin" />}
                    {status === 'DONE'  && <CheckCircle2 className="w-3.5 h-3.5 text-green-500" />}
                    <span className="text-xs font-bold text-zinc-600">{STATUS_LABELS[status as keyof typeof STATUS_LABELS]}</span>
                    <span className="ml-auto text-xs text-zinc-400 font-mono">{statusItems.length}</span>
                  </div>
                  {statusItems.length === 0
                    ? <div className="rounded-xl border-2 border-dashed border-zinc-200 dark:border-zinc-700 py-8 text-center text-xs text-zinc-400">
                        {status === 'TODO' ? 'Adicione tarefas com "+ Nova Tarefa"' : status === 'DOING' ? 'Mova tarefas para cá' : 'Tarefas concluídas aparecem aqui'}
                      </div>
                    : statusItems.map((t) => (
                        <TaskCard key={t.id} task={t} onStatusChange={statusChange} onEdit={(task) => { setEditTask(task); setShowForm(false) }} />
                      ))
                  }
                </div>
              )
            })}
          </div>
        </div>
      )}
    </div>
  )
}
