/**
 * GET /api/admin/ceo-tasks/insights
 * OKR Dashboard: progresso de faturamento, burn rate, CAC, alertas.
 *
 * Metas configuráveis (hardcoded para MVP — migrar para Settings):
 *   REVENUE_GOAL  = R$ 1.000.000 / mês
 *   BURN_RATE_MAX = R$   300.000 / mês
 *   CAC_ALERT     = R$     500 por cliente
 */
import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth/next'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

const REVENUE_GOAL  = 1_000_000
const BURN_RATE_MAX =   300_000
const CAC_ALERT_PCT = 0.10   // CAC > 10% da meta = alerta

export async function GET(req: globalThis.Request) {
  const session = await getServerSession(authOptions)
  if (!session?.user?.role || session.user.role !== 'ADMIN')
    return NextResponse.json({ error: 'Acesso restrito ao CEO' }, { status: 403 })

  const { searchParams } = new URL(req.url)
  const year  = parseInt(searchParams.get('year')  ?? String(new Date().getFullYear()), 10)
  const month = parseInt(searchParams.get('month') ?? String(new Date().getMonth() + 1), 10)
  const monthStart = new Date(year, month - 1, 1)
  const monthEnd   = new Date(year, month,     1)

  // ── Faturamento Realizado (AssetSalesOrder DELIVERED no mês) ─────────────
  const revAgg = await prisma.assetSalesOrder.aggregate({
    where:  { status: { in: ['DELIVERED', 'DELIVERING'] }, deliveredAt: { gte: monthStart, lt: monthEnd } },
    _sum:   { negotiatedPrice: true, grossMargin: true, costSnapshot: true },
    _count: true,
  })
  const revenue     = Number(revAgg._sum.negotiatedPrice ?? 0)
  const grossMargin = Number(revAgg._sum.grossMargin ?? 0)
  const cogs        = Number(revAgg._sum.costSnapshot ?? 0)
  const salesCount  = revAgg._count

  // ── Burn Rate (PurchaseOrders pagas no mês) ───────────────────────────────
  const burnAgg = await prisma.purchaseOrder.aggregate({
    where:  { status: { in: ['PAID', 'PARTIALLY_PAID'] }, paidAt: { gte: monthStart, lt: monthEnd } },
    _sum:   { totalAmount: true },
  })
  const burnRate = Number(burnAgg._sum.totalAmount ?? 0)

  // ── Faturamento dos últimos 6 meses (para sparkline) ─────────────────────
  const monthlyRevenue: { month: string; revenue: number; margin: number }[] = []
  for (let i = 5; i >= 0; i--) {
    const d    = new Date(year, month - 1 - i, 1)
    const dEnd = new Date(year, month     - i, 1)
    const agg  = await prisma.assetSalesOrder.aggregate({
      where: { status: { in: ['DELIVERED', 'DELIVERING'] }, deliveredAt: { gte: d, lt: dEnd } },
      _sum:  { negotiatedPrice: true, grossMargin: true },
    })
    monthlyRevenue.push({
      month:   d.toLocaleString('pt-BR', { month: 'short', year: '2-digit' }),
      revenue: Number(agg._sum.negotiatedPrice ?? 0),
      margin:  Number(agg._sum.grossMargin ?? 0),
    })
  }

  // ── CAC — Custo de Aquisição de Cliente ──────────────────────────────────
  // CAC = gasto com compras / número de vendas entregues
  const cac         = salesCount > 0 ? burnRate / salesCount : 0
  const cacAlert    = cac > REVENUE_GOAL * CAC_ALERT_PCT
  const cacStatus   = cac === 0 ? 'NO_DATA' : cacAlert ? 'DANGER' : 'OK'

  // ── Progresso das metas ───────────────────────────────────────────────────
  const revenuePct  = Math.min(100, Math.round((revenue  / REVENUE_GOAL)  * 100))
  const burnPct     = Math.min(100, Math.round((burnRate / BURN_RATE_MAX) * 100))
  const marginPct   = revenue > 0 ? Math.round((grossMargin / revenue) * 100) : 0

  // ── Alerta de CAC automático: cria tarefa se necessário ──────────────────
  if (cacAlert) {
    const exists = await prisma.ceoTask.findFirst({
      where: { title: { contains: 'Emergência: CAC Elevado' }, status: { not: 'DONE' } },
    })
    if (!exists) {
      await prisma.ceoTask.create({
        data: {
          title:         `Emergência: CAC Elevado — R$${Math.round(cac).toLocaleString('pt-BR')}`,
          description:   `O Custo de Aquisição de Cliente atingiu R$${Math.round(cac).toLocaleString('pt-BR')} este mês, ultrapassando ${Math.round(CAC_ALERT_PCT * 100)}% da meta mensal. Otimize o funil de vendas imediatamente.`,
          category:      'ESCALA',
          impact:        10,
          urgency:       10,
          priorityScore: 30,
          priority:      'CRITICAL',
          autoGenerated: true,
          status:        'TODO',
        },
      })
    }
  }

  // ── Alerta de Burn Rate: avisa quando > 80% do teto ──────────────────────
  const burnAlert = burnRate > BURN_RATE_MAX * 0.8
  if (burnAlert) {
    const exists = await prisma.ceoTask.findFirst({
      where: { title: { contains: 'Burn Rate Crítico' }, status: { not: 'DONE' } },
    })
    if (!exists) {
      await prisma.ceoTask.create({
        data: {
          title:         `Burn Rate Crítico — ${burnPct}% do teto de R$${BURN_RATE_MAX.toLocaleString('pt-BR')}`,
          description:   `Gastos operacionais atingiram R$${burnRate.toLocaleString('pt-BR')} de R$${BURN_RATE_MAX.toLocaleString('pt-BR')} permitidos. Revise compras de ativos e custos fixos.`,
          category:      'EFICIENCIA',
          impact:        9,
          urgency:       9,
          priorityScore: 27,
          priority:      'CRITICAL',
          autoGenerated: true,
          status:        'TODO',
        },
      })
    }
  }

  // ── Dias restantes no mês ──────────────────────────────────────────────────
  const today     = new Date()
  const daysLeft  = Math.max(0, Math.ceil((monthEnd.getTime() - today.getTime()) / 86400000))
  const dailyNeed = daysLeft > 0 ? Math.round((REVENUE_GOAL - revenue) / daysLeft) : 0

  // ── Contagem de tarefas por status ────────────────────────────────────────
  const taskStats = await prisma.ceoTask.groupBy({
    by: ['status'],
    _count: true,
    where:  { status: { not: 'ARCHIVED' } },
  })

  return NextResponse.json({
    period: { year, month, daysLeft, dailyNeed },
    revenue: {
      realized:   revenue,
      goal:       REVENUE_GOAL,
      pct:        revenuePct,
      grossMargin,
      marginPct,
      cogs,
      salesCount,
      onTrack:    revenue >= (REVENUE_GOAL / 30) * (new Date().getDate()),
    },
    burnRate: {
      spent:    burnRate,
      limit:    BURN_RATE_MAX,
      pct:      burnPct,
      alert:    burnAlert,
      remaining: Math.max(0, BURN_RATE_MAX - burnRate),
    },
    cac: { value: Math.round(cac), alert: cacAlert, status: cacStatus, limit: REVENUE_GOAL * CAC_ALERT_PCT },
    monthlyRevenue,
    taskStats: Object.fromEntries(taskStats.map((t) => [t.status, t._count])),
    alerts: {
      cac:      cacAlert,
      burnRate: burnAlert,
      messages: [
        cacAlert      ? `🚨 CAC em R$${Math.round(cac).toLocaleString('pt-BR')} — acima do limite` : null,
        burnAlert     ? `🔴 Burn Rate em ${burnPct}% do teto` : null,
        revenue < (REVENUE_GOAL * 0.3) && new Date().getDate() > 15 ? `⚠️ Faturamento abaixo de 30% da meta na segunda quinzena` : null,
      ].filter(Boolean),
    },
  })
}
